# From Spring Security documentation:
# Public Clients are supported using Proof Key for Code Exchange (PKCE). PKCE will automatically be used when client-authentication-method is set to "none"
# see https://docs.spring.io/spring-security/reference/reactive/oauth2/client/client-authentication.html#oauth2-client-authentication-public
spring.security.oauth2.client.registration.keycloak.client-id=ysg-manager-server
spring.security.oauth2.client.registration.keycloak.client-authentication-method=none
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.provider.keycloak.issuer-uri=https://lemur-10.cloud-iam.com/auth/realms/ysg-manager
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://lemur-10.cloud-iam.com/auth/realms/ysg-manager

spring.cloud.gcp.sql.enabled=false

spring.h2.console.enabled=false
