name: Java CI

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build with Maven
        run: mvn -B clean install --file pom.xml
      - name: Build and Publish Image
        run: mvn -B clean spring-boot:build-image --file ./ysg-manager-server/pom.xml -Pskip-tests  -DysgDockerHubUsername=${{secrets.DOCKER_HUB_USERNAME}} -DysgDockerHubPassword=${{secrets.DOCKER_HUB_PASSWORD}}
